services:

  php:
    build: 
      context: ./docker/php
    volumes:
      - ./wordpress:/var/www/html:rw,cached
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/themes:/var/www/html/wp-content/themes
    ports:
      - "9000:9000"

  server:
    image: nginx:latest
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always
  
  db:
    image: mariadb:11.2
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - 3306:3306
  
  wp:
    build:
      context: ./docker/php
      target: cli
    user: "${HOST_USER_ID}:${HOST_GROUP_ID}"
    volumes:
      - ./wordpress:/var/www/html
      - ./src:/var/www/html/wp-content
    entrypoint: ["wp"]
    tty: true
    working_dir: /var/www/html